/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  corePlugins: { preflight: false },
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "secondary-fixed": "#ffdbcb",
        "secondary-container": "#ff7a2c",
        "tertiary-container": "#005915",
        "secondary-fixed-dim": "#ffb692",
        "on-tertiary-fixed": "#002204",
        "on-error": "#ffffff",
        "inverse-on-surface": "#eaf1ff",
        "surface-bright": "#f8f9ff",
        "inverse-primary": "#abc7ff",
        "on-primary-container": "#9bbdff",
        "error": "#ba1a1a",
        "background": "#f8f9ff",
        "on-tertiary": "#ffffff",
        "outline": "#737783",
        "outline-variant": "#c2c6d3",
        "surface-container-high": "#dce9ff",
        "primary": "#00346f",
        "primary-container": "#004a99",
        "on-tertiary-fixed-variant": "#005313",
        "on-primary": "#ffffff",
        "inverse-surface": "#213145",
        "on-surface": "#0b1c30",
        "primary-fixed": "#d7e2ff",
        "surface-dim": "#cbdbf5",
        "on-surface-variant": "#424751",
        "surface-container": "#e5eeff",
        "tertiary-fixed-dim": "#78dc77",
        "surface-tint": "#255dad",
        "surface": "#f8f9ff",
        "surface-container-highest": "#d3e4fe",
        "on-secondary-container": "#612500",
        "tertiary": "#003f0c",
        "on-secondary-fixed": "#341100",
        "on-background": "#0b1c30",
        "on-secondary-fixed-variant": "#793000",
        "secondary": "#9f4200",
        "primary-fixed-dim": "#abc7ff",
        "tertiary-fixed": "#94f990",
        "error-container": "#ffdad6",
        "surface-variant": "#d3e4fe",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#001b3f",
        "on-primary-fixed-variant": "#00458f",
        "on-error-container": "#93000a",
        "on-secondary": "#ffffff",
        "surface-container-low": "#eff4ff",
        "on-tertiary-container": "#6ed26e"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "margin-desktop": "64px",
        "margin-mobile": "16px",
        "lg": "24px",
        "xl": "40px",
        "gutter": "24px",
        "md": "16px",
        "sm": "8px",
        "xs": "4px",
        "base": "4px"
      },
      "fontFamily": {
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "title-md": ["Inter", "sans-serif"]
      },
      "fontSize": {
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "label-md": ["14px", {"lineHeight": "20px", "fontWeight": "500"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500"}],
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "fontWeight": "600"}],
        "title-md": ["18px", {"lineHeight": "24px", "fontWeight": "600"}]
      }
    }
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
